(function(){
var selector='button,a,input,select,[role="button"],.server-card,.cat-item,.ch-grid-item,.media-grid-item,.ls-tile,.ls-side-btn,.match-card,.league';
var current=-1;
function items(){var a=document.querySelectorAll(selector),r=[];for(var i=0;i<a.length;i++){var e=a[i],s=getComputedStyle(e);if(s.display!=='none'&&s.visibility!=='hidden'&&e.offsetWidth>0&&e.offsetHeight>0&&!e.disabled)r.push(e);}return r;}
function focusAt(n){var a=items();if(!a.length)return;current=(n+a.length)%a.length;for(var i=0;i<a.length;i++)a[i].classList.remove('tv-focus');var e=a[current];e.classList.add('tv-focus');try{e.focus();e.scrollIntoView({block:'nearest',inline:'nearest'});}catch(x){} }
function activate(){var a=items();if(current>=0&&a[current]){try{a[current].click();}catch(x){}}}
document.addEventListener('keydown',function(e){var k=e.key||e.code||'';if(k==='ArrowRight'||k==='Right'){e.preventDefault();focusAt(current+1);}else if(k==='ArrowLeft'||k==='Left'){e.preventDefault();focusAt(current-1);}else if(k==='ArrowDown'||k==='Down'||k==='PageDown'){e.preventDefault();focusAt(current+1);}else if(k==='ArrowUp'||k==='Up'||k==='PageUp'){e.preventDefault();focusAt(current-1);}else if(k==='Enter'||k==='NumpadEnter'||k==='OK'||k==='Select'){e.preventDefault();activate();}else if(k==='Escape'||k==='Backspace'||k==='BrowserBack'||k==='GoBack'){e.preventDefault();if(typeof closePlayerOverlay==='function'&&document.getElementById('playerOverlay')&&document.getElementById('playerOverlay').classList.contains('open'))closePlayerOverlay();else if(typeof closeCatDrawer==='function'&&document.getElementById('catDrawer')&&document.getElementById('catDrawer').classList.contains('open'))closeCatDrawer();else if(typeof goToServerSelection==='function'&&document.getElementById('appShell')&&document.getElementById('appShell').classList.contains('show'))goToServerSelection();}else if(k==='Home'){e.preventDefault();focusAt(0);}else if(k==='End'){e.preventDefault();focusAt(items().length-1);}},false);
document.addEventListener('mouseover',function(e){var t=e.target.closest?e.target.closest(selector):null;if(t){var a=items();for(var i=0;i<a.length;i++)if(a[i]===t){current=i;break;}for(var j=0;j<a.length;j++)a[j].classList.remove('tv-focus');t.classList.add('tv-focus');}},false);
window.addEventListener('load',function(){setTimeout(function(){if(items().length)focusAt(0);},700);});
})();
